# A simple script to clean the .MD files generated by Knitr so they can be posted directly to blogspot with proper image links
cleanup <- function(filename, yaml = NULL, repo) {
  post <- readLines(filename)
  post <- gsub(".png",".png?raw=TRUE",post,fixed=TRUE)
  post <- gsub("![](",paste0("![](https://github.com/xmarquez/",repo,"/raw/master/"),post,fixed=TRUE)
  if(!is.null(yaml)){
    post <- c(yaml,post[2:length(post)])
  } else {
    post <- post[2:length(post)]
  }
  writeLines(post,filename)
}

cleanup("Culture_and_Democracy.md",
        yaml=c("---","title: 'What do People Think of Democracy? And Does it Matter?'","---"),
        repo="WorldValuesSurvey")